name: racon CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image:
          - gcc:7
          - silkeh/clang:7
        build_type:
          - Debug
          - Release
    container:
      image: ${{ matrix.image }}
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          chmod +x ci/install_deps.sh
          ./ci/install_deps.sh


      - name: Generate build files
        run: >
          cmake -B ./build -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ./build

      - name: Test
        run: |
          ./build/bin/racon --version
          ./build/bin/racon_test
