name: racon CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - gcc:7
          - silkeh/clang:7
        build_type:
          - Debug, Release
    container:
      image: ${{ matrix.image }}
      options: --user root

    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          chmod +x ci/install_deps.sh
          ./ci/install_deps.sh

      - name: Create build directory
        run: cmake -E make_directory build

      - name: Generate build files
        working-directory: build
        run: >
          cmake ..
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        working-directory: build
        run: cmake --build .

      - name: Test
        working-directory: build
        run: |
          bin/racon --version
          bin/racon_test
